[directory]
truncation_length = 10
truncate_to_repo = false

[git_status]
conflicted = "💥"
ahead = "🏎💨"
behind = "🥲"
diverged = "😵"
untracked = "🌚"
stashed = "📦"
modified = "📝"
staged = '🔦'
renamed = "🏷"
deleted = "🗑"

[gcloud]
disabled = true

[battery]
disabled = true

[time]
disabled = true

[memory_usage]
disabled = true

[username]
disabled = true

[hostname]
disabled = true
